server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 80
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev


  devtools:
    restart:
      enabled: true
  mail:
    host: smtp.qq.com
    username: ykbian@qq.com
    password: iioqadywnbrhbcij
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
        #debug: true

#spring.mail.host=smtp.qq.com
#spring.mail.username=393156105@qq.com
#spring.mail.password=tdckceislhfibhbbb
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#
#  cache:
#    type: ehcache
#    ehcache:
#      config: config/ehcache.xml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapping/**/*Mapper.xml
  typeAliasesPackage: com.byk.myboke.**.entity
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
